using System;
using System.Collections.Generic;
using System.Text;

namespace SWGOH_Prereqs
{
    class GuildToon
    {
        public int members { get; set; }
        public bool isShip { get; set; }
        public int totalCount { get; set; }
        public int[] stars = new int[3];
        public int[] zetas = new int[6];
        public int[] relics = new int[8];
        public int[] gearLevel = new int[9];
        public int gearEquipped { get; set; }
        public List<PlayerToon> players = new List<PlayerToon>();
        public GuildToon() { }
    }

    class PlayerToon
    {
        public string name { get; set; }
        public int GP { get; set; }
        public int level { get; set; }
        public long star { get; set; }
        public long gearLevel { get; set; }
        public int gearEquipped { get; set; }
        public long relic { get; set; }
        public int zetas { get; set; }
        public double speed { get; set; }
        public double offense { get; set; }
        public PlayerToon() { }
        public void setName(string rName)
        {
            name = rName;
        }
    }
    class CharacterDefID
    {
        public Dictionary<string, string> toons = new Dictionary<string, string>()
        {
            {"MAGMATROOPER", "Magma Trooper" },
            {"HERMITYODA", "Hermit Yoda"},
            {"ZEBS3", "Zeb" },
            {"BARRISSOFFEE", "Barriss Offee" },
            {"CT210408", "ECHO" },
            {"B1BATTLEDROIDV2", "B1" },
            {"COLONELSTARCK", "Colonel Starck" },
            {"TIEFIGHTERFOSF", "FOSF Tie Fighter" },
            {"BB8", "BB8" },
            {"POGGLETHELESSER", "Poggle" },
            {"FIRSTORDERSPECIALFORCESPILOT", "FOSF Tie Pilot" },
            {"GENERALKENOBI", "GK" },
            {"JAWASCAVENGER", "Jawa Scavenger" },
            {"L3_37", "L337" },
            {"DROIDEKA", "Droideka" },
            {"EWOKSCOUT", "Ewok Scout" },
            {"SITHINFILTRATOR", "Scimitar" },
            {"K2SO", "K2SO" },
            {"SITHTROOPER", "Sith Trooper" },
            {"IG86SENTINELDROID", "IG 86" },
            {"SITHMARAUDER", "Sith Marauder" },
            {"REYJEDITRAINING", "Rey (Jedi Training)" },
            {"KYLOREN", "Kylo Ren" },
            {"DENGAR", "Dengar" },
            {"ARC170REX", "Arc 170" },
            {"TIEFIGHTERFIRSTORDER", "FO Tie Fighter" },
            {"MAGNAGUARD", "Magnaguard" },
            {"MILLENNIUMFALCONEP7", "Rey's Falcon" },
            {"RANGETROOPER", "Range Trooper" },
            {"QUIGONJINN", "Qui-gon Jinn" },
            {"ROYALGUARD", "Royal Guard" },
            {"GEONOSIANSPY", "Geo Spy" },
            {"BASTILASHAN", "Bastila Shan" },
            {"JAWA", "Jawa" },
            {"SITHFIGHTER", "Sith Fighter" },
            {"XWINGRESISTANCE", "Resistance X-Wing" },
            {"QIRA", "Qi'ra" },
            {"POE", "Poe Dameron" },
            {"TALIA", "Talia" },
            {"NIGHTSISTERZOMBIE", "NS Zombie" },
            {"SCARIFREBEL", "Scarif Rebel Pathfinder" },
            {"GRANDADMIRALTHRAWN", "Thrawn" },
            {"JEDISTARFIGHTERANAKIN", "Eta 2" },
            {"IMPERIALPROBEDROID", "IPD" },
            {"SABINEWRENS3", "Sabine" },
            {"PAPLOO", "Paploo" },
            {"YOUNGHAN", "Young Han" },
            {"EWOKELDER", "Ewok Elder" },
            {"CHIEFCHIRPA", "Chief Chirpa" },
            {"GENERALHUX", "General Hux" },
            {"CT5555", "Fives" },
            {"VISASMARR", "Visas Marr" },
            {"LUKESKYWALKER", "Farmboy Luke" },
            {"KITFISTO", "Kit Fisto" },
            {"HOUNDSTOOTH", "Hound's Tooth" },
            {"ADMINISTRATORLANDO", "Lando" },
            {"ANAKINKNIGHT", "JKA" },
            {"IG2000", "IG-2000" },
            {"NIGHTSISTERSPIRIT", "NS Spirit" },
            {"XANADUBLOOD", "Xanadu Blood" },
            {"CLONESERGEANTPHASEI", "Clone Sergeant" },
            {"ADMIRALACKBAR", "Admiral Ackbar" },
            {"FULCRUMAHSOKA", "Ahsoka (Fulcrum)" },
            {"STORMTROOPER", "Stormtrooper" },
            {"LUMINARAUNDULI", "Luminara" },
            {"JANGOFETT", "Jango Fett" },
            {"HOTHREBELSCOUT", "Hoth Rebel Scout" },
            {"GHOST", "Ghost" },
            {"NUTEGUNRAY", "Nute Gunray" },
            {"SLAVE1", "Slave 1" },
            {"TIEADVANCED", "Tie Advanced" },
            {"VEERS", "General Veers" },
            {"PAO", "Pao" },
            {"IG88", "IG-88" },
            {"MILLENNIUMFALCONPRISTINE", "Lando's Falcon" },
            {"EBONHAWK", "Ebon Hawk" },
            {"REY", "Scavenger Rey" },
            {"BLADEOFDORIN", "Plo Koon's Star Fighter" },
            {"DARTHNIHILUS", "DN" },
            {"EMPERORPALPATINE", "Palpatine" },
            {"PLOKOON", "Plo Koon" },
            {"DAKA", "Daka" },
            {"GRANDMOFFTARKIN", "Tarkin" },
            {"LOGRAY", "Logray" },
            {"GEONOSIANSOLDIER", "Geo Soldier" },
            {"VULTUREDROID", "Vulture Droid" },
            {"RESISTANCETROOPER", "Resistance Trooper" },
            {"HK47", "HK-47" },
            {"TUSKENRAIDER", "Tusken Raider" },
            {"CASSIANANDOR", "Cassian" },
            {"DARTHTRAYA", "Traya" },
            {"BAZEMALBUS", "Baze" },
            {"EPIXFINN", "Res Hero Finn" },
            {"ZAALBAR", "Zaalbar" },
            {"KCLONEWARSCHEWBACCA2SO", "CW Chewbacca" },
            {"COMMANDERLUKESKYWALKER", "CLS" },
            {"B2SUPERBATTLEDROID", "B2" },
            {"UWINGROGUEONE", "Cassian's U-Wing" },
            {"DARTHSIDIOUS", "Sidious" },
            {"OLDBENKENOBI", "Old Ben" },
            {"KYLORENUNMASKED", "Kylo Ren (Unmasked)" },
            {"YOUNGCHEWBACCA", "Young Chewbacca" },
            {"YOUNGLANDO", "Young Lando" },
            {"HANSOLO", "Han Solo" },
            {"SMUGGLERHAN", "Vet Han" },
            {"UGNAUGHT", "Ugnaught" },
            {"FOSITHTROOPER", "FO Sith Trooper" },
            {"UMBARANSTARFIGHTER", "Umbaran" },
            {"WAMPA", "Wampa" },
            {"SMUGGLERCHEWBACCA", "Vet Chewbacca" },
            {"R2D2_LEGENDARY", "R2D2" },
            {"UWINGSCARIF", "Bistan's U-Wing" },
            {"HUMANTHUG", "Mob Enforcer" },
            {"GARSAXON", "Gar Saxon" },
            {"CORUSCANTUNDERWORLDPOLICE", "CUP" },
            {"ENFYSNEST", "Nest" },
            {"MOTHERTALZIN", "MT" },
            {"BIGGSDARKLIGHTER", "Biggs" },
            {"CC2224", "Cody" },
            {"C3POLEGENDARY", "C3PO" },
            {"JEDIKNIGHTREVAN", "JKR" },
            {"PADMEAMIDALA", "Padme" },
            {"NIGHTSISTERINITIATE", "NS Initiate" },
            {"CT7567", "Rex" },
            {"EMPERORSSHUTTLE", "Emperor's Shuttle" },
            {"ZAMWESELL", "Zam" },
            {"CAPITALMONCALAMARICRUISER", "Home One" },
            {"SUNFAC", "Sun Fac" },
            {"LOBOT", "Lobot" },
            {"EMBO", "Embo" },
            {"IMAGUNDI", "Ima Gun Di" },
            {"TIESILENCER", "Tie Silencer" },
            {"YWINGCLONEWARS", "Y-Wing" },
            {"XWINGRED3", "Biggs' X-Wing" },
            {"EETHKOTH", "Eeth Koth" },
            {"CAPITALSTARDESTROYER", "Executrix" },
            {"T3_M4", "T3-M4" },
            {"XWINGRED2", "Wedge's X-Wing" },
            {"JEDISTARFIGHTERAHSOKATANO", "Ahsoka's Star Fighter" },
            {"HOTHREBELSOLDIER", "Hoth Rebel Soldier" },
            {"ASAJVENTRESS", "Asajj Ventress" },
            {"GRIEVOUS", "GG" },
            {"CHIRRUTIMWE", "Chirrut" },
            {"JUHANI", "Juhani" },
            {"CAPITALNEGOTIATOR", "Negotiator" },
            {"KANANJARRUSS3", "Kanan" },
            {"ROSETICO", "Rose Tico" },
            {"JEDIKNIGHTCONSULAR", "Consular" },
            {"AHSOKATANO", "Ahsoka Tano" },
            {"DIRECTORKRENNIC", "Krennic" },
            {"TIEFIGHTERIMPERIAL", "Imperial Tie Fighter" },
            {"STORMTROOPERHAN", "ST Han" },
            {"HERASYNDULLAS3", "Hera" },
            {"BASTILASHANDARK", "BSF" },
            {"BOSSK", "Bossk" },
            {"FIRSTORDEREXECUTIONER", "FOX" },
            {"VADER", "Vader" },
            {"COUNTDOOKU", "Count Dooku" },
            {"MISSIONVAO", "Mission Vao" },
            {"ARC170CLONESERGEANT", "Sergeant's ARC 170" },
            {"GEONOSIANBROODALPHA", "GBA" },
            {"MAUL", "Darth Maul" },
            {"JOLEEBINDO", "Jolee" },
            {"CHIEFNEBIT", "Chief Nebit" },
            {"TUSKENSHAMAN", "Tusken Shaman" },
            {"IMPERIALSUPERCOMMANDO", "Imperial Super Commando" },
            {"FIRSTORDERTIEPILOT", "FO Tie Pilot" },
            {"DARTHSION", "Sion" },
            {"CAPITALJEDICRUISER", "Endurance" },
            {"CAPITALCHIMAERA", "Chimaera" },
            {"COMMANDSHUTTLE", "Command Shuttle" },
            {"FIRSTORDERTROOPER", "FO Stormtrooper" },
            {"PHANTOM2", "Phantom" },
            {"HOTHLEIA", "ROLO" },
            {"GREEDO", "Greedo" },
            {"BODHIROOK", "Bodhi Rook" },
            {"CHEWBACCALEGENDARY", "Chewbacca" },
            {"CHOPPERS3", "Chopper" },
            {"BOBAFETT", "Boba Fett" },
            {"WEDGEANTILLES", "Wedge" },
            {"DEATHTROOPER", "Death Trooper" },
            {"CARTHONASI", "Carth" },
            {"ARCTROOPER501ST", "ARC Trooper" },
            {"WICKET", "Wicket" },
            {"GEONOSIANSTARFIGHTER2", "Geo Soldier's Starfighter" },
            {"GEONOSIANSTARFIGHTER1", "Sun Fac's Starfighter" },
            {"GEONOSIANSTARFIGHTER3", "Geo Spy's Starfighter" },
            {"MACEWINDU", "Mace" },
            {"DATHCHA", "Datcha" },
            {"JYNERSO", "Jyn Erso" },
            {"TEEBO", "Teebo" },
            {"XWINGBLACKONE", "Poe's X-Wing" },
            {"SITHBOMBER", "B28" },
            {"AMILYNHOLDO", "Holdo" },
            {"GAUNTLETSTARFIGHTER", "Gauntlet Starfighter" },
            {"SITHASSASSIN", "Sith Assassin" },
            {"SNOWTROOPER", "Snowtrooper" },
            {"SHORETROOPER", "Shoretrooper" },
            {"PRINCESSLEIA", "Princess Leia" },
            {"SAVAGEOPRESS", "Savage" },
            {"FINN", "Finn" },
            {"PHASMA", "Captain Phasma" },
            {"EZRABRIDGERS3", "Ezra" },
            {"TIEREAPER", "Tie Reaper" },
            {"HYENABOMBER", "Hyena Bomber" },
            {"JEDISTARFIGHTERCONSULAR", "Consular's Starfighter" },
            {"FIRSTORDEROFFICERMALE", "FO Officer" },
            {"RESISTANCEPILOT", "Resistance Pilot" },
            {"AURRA_SING", "Aurra Sing" },
            {"JEDIKNIGHTGUARDIAN", "JKG" },
            {"CANDEROUSORDO", "Canderous" },
            {"CADBANE", "Cad Bane" },
            {"TIEFIGHTERPILOT", "TFP" },
            {"GRANDMASTERYODA", "GMY" },
            {"SHAAKTI", "Shaak Ti" },
            {"BISTAN", "Bistan" },
            {"DARTHMALAK", "Malak" },
            {"JAWAENGINEER", "Jawa Engineer" },
            {"AAYLASECURA", "Aayla Secura" },
            {"WATTAMBOR", "Wat Tambor" },
            {"DARTHREVAN", "DR" },
            {"URORRURRR", "URoRRuR'R'R" },
            {"NIGHTSISTERACOLYTE", "NS Acolyte" },
            {"GENERALSKYWALKER", "Gen Skywalker" },
            {"HOTHHAN", "Captain Han" },
            {"GAMORREANGUARD", "Gamorrean Guard" },
            {"SUPREMELEADERKYLOREN", "GL Kylo" },
            {"GLREY", "GL Rey" },
            { "CAPITALMALEVOLENCE", "Malevolence" },
            { "MILLENNIUMFALCON", "Mil Falcon" },
            {"Rebel Y Wing","YWINGREBEL"},
                { "THEMANDALORIAN","Mando"},
                { "GREEFKARGA","Greef Karga"},
                { "CARADUNE","Cara Dune"},
                { "TIEBOMBERIMPERIAL","Tie Bomber"},
            {"JEDIKNIGHTLUKE", "JKL" },
            { "MONMOTHMA","Mon Mothma"  },
            {"C3POCHEWBACCA", "Threepio & Chewie" },
            {"GRANDMASTERLUKE", "GL Luke" },
            {"SITHPALPATINE", "GL Palp" },
            {"ADMIRALPIETT", "Admiral Piett"}
        };
        public CharacterDefID() { }
    }
    class CharacterStrings
    {
        public SortedDictionary<string, string> toonsList = new SortedDictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
         { "Magma Trooper", "MAGMATROOPER"},{ "Hermit Yoda","HERMITYODA"},{ "Zeb", "ZEBS3"},{ "Barriss Offee", "BARRISSOFFEE"},{ "ECHO", "CT210408"},{ "B1", "B1BATTLEDROIDV2"},{ "Colonel Starck", "COLONELSTARCK"},{ "FOSF Tie Fighter", "TIEFIGHTERFOSF"},{ "FOSFTF", "TIEFIGHTERFOSF"},{ "BB8", "BB8"},{ "Poggle", "POGGLETHELESSER"},
            { "FOSF Tie Pilot", "FIRSTORDERSPECIALFORCESPILOT"},{ "FOSFTP", "FIRSTORDERSPECIALFORCESPILOT"},{ "GK", "GENERALKENOBI"},{ "Jawa Scavenger", "JAWASCAVENGER"},{ "L337", "L3_37"},{ "L3", "L3_37"},{ "Droideka" ,"DROIDEKA"},{ "DDK" ,"DROIDEKA"},{ "Ewok Scout", "EWOKSCOUT"},{ "Scimitar", "SITHINFILTRATOR"},{ "K2SO", "K2SO"},
            { "Sith Empire Trooper", "SITHTROOPER"},{ "SET", "SITHTROOPER"},{ "IG 86", "IG86SENTINELDROID"},{ "Sith Marauder", "SITHMARAUDER"},{ "Rey (Jedi Training)", "REYJEDITRAINING"},{ "RJT", "REYJEDITRAINING"},{ "JTR", "REYJEDITRAINING"},{ "Kylo Ren", "KYLOREN"},{ "Kylo", "KYLOREN"},{ "Dengar", "DENGAR"},{ "Arc 170", "ARC170REX"},
            { "FO Tie Fighter", "TIEFIGHTERFIRSTORDER"},{ "Magnaguard", "MAGNAGUARD"},{ "Rey's Falcon", "MILLENNIUMFALCONEP7"},{ "Range Trooper", "RANGETROOPER"},{ "Qui-gon Jinn", "QUIGONJINN"},{ "Royal Guard", "ROYALGUARD"},{ "Geo Spy", "GEONOSIANSPY"},{ "Bastila Shan", "BASTILASHAN"},{ "Jawa", "JAWA"},{ "Sith Fighter", "SITHFIGHTER"},
            { "Resistance X-Wing", "XWINGRESISTANCE"},{ "Qi'ra", "QIRA"},{ "Poe Dameron", "POE"},{ "Talia", "TALIA"},{ "NS Zombie", "NIGHTSISTERZOMBIE"},{ "Zombie", "NIGHTSISTERZOMBIE"},{ "Scarif Rebel Pathfinder", "SCARIFREBEL"},{ "Thrawn", "GRANDADMIRALTHRAWN"},{ "Eta 2", "JEDISTARFIGHTERANAKIN"},{ "IPD", "IMPERIALPROBEDROID"},
            { "Sabine", "SABINEWRENS3"},{ "Paploo", "PAPLOO"},{ "Young Han", "YOUNGHAN"},{ "Ewok Elder", "EWOKELDER"},{ "Chief Chirpa", "CHIEFCHIRPA"},{ "General Hux", "GENERALHUX"},{ "Hux", "GENERALHUX"},{ "Fives", "CT5555"},{ "5s", "CT5555"},{ "Visas Marr", "VISASMARR"},{ "Farmboy Luke", "LUKESKYWALKER"},{ "Kit Fisto", "KITFISTO"},
            { "Hound's Tooth", "HOUNDSTOOTH"},{ "Lando", "ADMINISTRATORLANDO"},{ "JKA", "ANAKINKNIGHT"},{ "IG-2000", "IG2000"},{ "NS Spirit", "NIGHTSISTERSPIRIT"},{ "Xanadu Blood", "XANADUBLOOD"},{ "Clone Sergeant", "CLONESERGEANTPHASEI"},{ "Admiral Ackbar", "ADMIRALACKBAR"},{ "Ahsoka (Fulcrum)", "FULCRUMAHSOKA"},{ "Stormtrooper", "STORMTROOPER"},
            { "Luminara", "LUMINARAUNDULI"},{ "Jango Fett", "JANGOFETT"},{ "Hoth Rebel Scout", "HOTHREBELSCOUT"},{ "Ghost" ,"GHOST"},{ "Nute Gunray", "NUTEGUNRAY"},{ "Slave 1" ,"SLAVE1"},{ "Tie Advanced", "TIEADVANCED"},{ "General Veers", "VEERS"},{ "Pao" ,"PAO"},{ "IG-88", "IG88"},{ "Lando's Falcon", "MILLENNIUMFALCONPRISTINE"},
            { "Ebon Hawk" ,"EBONHAWK"},
            { "Scavenger Rey", "REY"},
            { "Plo Koon's Star Fighter", "BLADEOFDORIN"},
            { "DN", "DARTHNIHILUS"},
            { "Palpatine", "EMPERORPALPATINE"},
            { "Plo Koon", "PLOKOON"},
            { "Daka", "DAKA"},
            { "Tarkin" ,"GRANDMOFFTARKIN"},
            { "Logray" ,"LOGRAY"},
            { "Geo Soldier" ,"GEONOSIANSOLDIER"},
            { "Vulture Droid", "VULTUREDROID"},
            { "Resistance Trooper", "RESISTANCETROOPER"},
            { "HK-47", "HK47"},
            { "Tusken Raider", "TUSKENRAIDER"},
            { "Cassian", "CASSIANANDOR"},
            { "Traya" ,"DARTHTRAYA"},
            { "Baze" ,"BAZEMALBUS"},
            { "Res Hero Finn", "EPIXFINN"},
            { "Zaalbar", "ZAALBAR"},
            { "CW Chewbacca", "KCLONEWARSCHEWBACCA2SO"},
            { "CLS" ,"COMMANDERLUKESKYWALKER"},
            { "B2" ,"B2SUPERBATTLEDROID"},
            { "Cassian's U-Wing", "UWINGROGUEONE"},
            { "Sidious" ,"DARTHSIDIOUS"},
            { "Old Ben", "OLDBENKENOBI"},
            { "Kylo Ren (Unmasked)", "KYLORENUNMASKED"},
            { "Young Chewbacca", "YOUNGCHEWBACCA"},
            { "Young Lando", "YOUNGLANDO"},
            { "Han Solo" ,"HANSOLO"},
            { "Vet Han" ,"SMUGGLERHAN"},
            { "Ugnaught", "UGNAUGHT"},
            { "FO Sith Trooper", "FOSITHTROOPER"},
            { "Sith Trooper", "FOSITHTROOPER"},
            { "Umbaran", "UMBARANSTARFIGHTER"},
            { "Wampa" ,"WAMPA"},
            { "Vet Chewbacca", "SMUGGLERCHEWBACCA"},
            { "R2D2" ,"R2D2_LEGENDARY"},
            { "Bistan's U-Wing", "UWINGSCARIF"},
            { "Mob Enforcer", "HUMANTHUG"},
            { "Gar Saxon", "GARSAXON"},
            { "CUP", "CORUSCANTUNDERWORLDPOLICE"},
            { "Nest", "ENFYSNEST"},
            { "MT", "MOTHERTALZIN"},
            { "Biggs", "BIGGSDARKLIGHTER"},
            { "Cody" ,"CC2224"},
            { "C3PO", "C3POLEGENDARY"},
            { "JKR", "JEDIKNIGHTREVAN"},
            { "Padme", "PADMEAMIDALA"},
            { "NS Initiate", "NIGHTSISTERINITIATE"},
            {"Rex" ,"CT7567"},
            { "Emperor's Shuttle", "EMPERORSSHUTTLE"},
            { "Zam", "ZAMWESELL"},
            { "Home One", "CAPITALMONCALAMARICRUISER"},
            { "Sun Fac", "SUNFAC"},
            { "Lobot" ,"LOBOT"},
            { "Embo" ,"EMBO"},
            { "Ima Gun Di", "IMAGUNDI"},
            { "Tie Silencer", "TIESILENCER"},
            { "Y-Wing" ,"YWINGCLONEWARS"},
            { "Biggs' X-Wing", "XWINGRED3"},
            { "Eeth Koth", "EETHKOTH"},
            { "Executrix" ,"CAPITALSTARDESTROYER"},
            { "T3-M4" ,"T3_M4"},
            { "Wedge's X-Wing", "XWINGRED2"},
            { "Ahsoka's Star Fighter", "JEDISTARFIGHTERAHSOKATANO"},
            {"Hoth Rebel Soldier", "HOTHREBELSOLDIER"},
            { "Asajj Ventress","ASAJVENTRESS"},
            { "GG", "GRIEVOUS"},
            { "Chirrut", "CHIRRUTIMWE"},
            { "Juhani" ,"JUHANI"},
            { "Negotiator", "CAPITALNEGOTIATOR"},
            { "Kanan", "KANANJARRUSS3"},
            { "Rose Tico", "ROSETICO"},
            { "Consular", "JEDIKNIGHTCONSULAR"},
            { "Ahsoka Tano", "AHSOKATANO"},
            { "Krennic", "DIRECTORKRENNIC"},
            { "Imperial Tie Fighter", "TIEFIGHTERIMPERIAL"},
            { "ST Han", "STORMTROOPERHAN"},
            { "Hera", "HERASYNDULLAS3"},
            { "BSF", "BASTILASHANDARK"},
            { "Bossk", "BOSSK"},
            { "FOX", "FIRSTORDEREXECUTIONER"},
            { "Vader", "VADER"},
            { "Count Dooku", "COUNTDOOKU"},
            { "Mission Vao", "MISSIONVAO"},
            { "Sergeant's ARC 170", "ARC170CLONESERGEANT"},
            { "GBA", "GEONOSIANBROODALPHA"},
            { "Darth Maul", "MAUL"},
            { "Jolee", "JOLEEBINDO"},
            { "Chief Nebit", "CHIEFNEBIT"},
            { "Tusken Shaman", "TUSKENSHAMAN"},
            { "Imperial Super Commando", "IMPERIALSUPERCOMMANDO"},
            { "FO Tie Pilot","FIRSTORDERTIEPILOT" },
            { "Sion", "DARTHSION"},
            { "Endurance", "CAPITALJEDICRUISER"},
            { "Chimaera","CAPITALCHIMAERA" },
            { "Command Shuttle","COMMANDSHUTTLE" },
            { "FO Stormtrooper","FIRSTORDERTROOPER" },
            { "Phantom","PHANTOM2" },
            { "ROLO", "HOTHLEIA"},
            { "Greedo" ,"GREEDO"},
            { "Bodhi Rook", "BODHIROOK"},
            { "Chewbacca","CHEWBACCALEGENDARY" },
            { "Chopper","CHOPPERS3" },
            { "Boba Fett", "BOBAFETT"},
            { "Wedge" ,"WEDGEANTILLES"},
            { "Death Trooper","DEATHTROOPER" },
            { "Carth" ,"CARTHONASI"},
            { "ARC Trooper", "ARCTROOPER501ST"},
            { "Wicket" ,"WICKET"},
            { "Geo Soldier's Starfighter", "GEONOSIANSTARFIGHTER2"},
            { "Sun Fac's Starfighter","GEONOSIANSTARFIGHTER1" },
            { "Geo Spy's Starfighter","GEONOSIANSTARFIGHTER3" },
            { "Mace","MACEWINDU" },
            { "Datcha","DATHCHA" },
            { "Jyn Erso","JYNERSO" },
            { "Teebo","TEEBO" },
            { "Poe's X-Wing","XWINGBLACKONE" },
            { "B28" ,"SITHBOMBER"},
            { "Holdo","AMILYNHOLDO" },
            { "Gauntlet Starfighter","GAUNTLETSTARFIGHTER" },
            { "Sith Assassin","SITHASSASSIN" },
            { "Snowtrooper","SNOWTROOPER" },
            { "Shoretrooper","SHORETROOPER" },
            { "Princess Leia","PRINCESSLEIA" },
            {"Savage","SAVAGEOPRESS" },
            {"Finn","FINN" },
            { "Captain Phasma","PHASMA" },
            { "Ezra","EZRABRIDGERS3" },
            { "Tie Reaper","TIEREAPER" },
            { "Hyena Bomber","HYENABOMBER" },
            { "Consular's Starfighter", "JEDISTARFIGHTERCONSULAR" },
            { "FO Officer","FIRSTORDEROFFICERMALE" },
            { "Resistance Pilot", "RESISTANCEPILOT" },
            { "Aurra Sing","AURRA_SING" },
            { "JKG", "JEDIKNIGHTGUARDIAN" },
            { "Canderous", "CANDEROUSORDO" },
            { "Cad Bane","CADBANE" },
            { "TFP","TIEFIGHTERPILOT" },
            { "GMY","GRANDMASTERYODA" },
            { "Shaak Ti","SHAAKTI" },
            { "Bistan","BISTAN" },
            { "Malak","DARTHMALAK" },
            { "Jawa Engineer", "JAWAENGINEER" },
            { "Aayla Secura","AAYLASECURA" },
            { "Wat Tambor","WATTAMBOR" },
            { "DR","DARTHREVAN" },
            { "URoRRuR'R'R","URORRURRR" },
            {"NS Acolyte","NIGHTSISTERACOLYTE" },
            {"Gen Skywalker","GENERALSKYWALKER" },
            {"GS","GENERALSKYWALKER" },
            {"GAS","GENERALSKYWALKER" },
            {"Captain Han", "HOTHHAN" },
            {"Gamorrean Guard","GAMORREANGUARD" },
            {"GL Kylo", "SUPREMELEADERKYLOREN" },
            {"SLKR", "SUPREMELEADERKYLOREN" },
            {"GL Rey", "GLREY"},
            {"Malevolence","CAPITALMALEVOLENCE" },
            {"Mil Falcon","MILLENNIUMFALCON"},
            {"Milf","MILLENNIUMFALCON"},
                {"Rebel Y Wing","YWINGREBEL"},
                { "mando","THEMANDALORIAN"},
                { "mandalorian","THEMANDALORIAN"},
                { "greef","GREEFKARGA"},
                { "cara","CARADUNE"},
                { "cara dune","CARADUNE"},
                { "Tie Bomber","TIEBOMBERIMPERIAL"},
            {"JKL","JEDIKNIGHTLUKE"  },
            {"Jedi Knight Luke","JEDIKNIGHTLUKE"  },
            {"Threepio & Chewie","C3POCHEWBACCA"  },
            {"Chewpio","C3POCHEWBACCA"  },
            { "Mon Mothma","MONMOTHMA"  },
            { "Mothma","MONMOTHMA"  },
            {"GL Luke","GRANDMASTERLUKE"},
            {"JML","GRANDMASTERLUKE"},
            {"GML","GRANDMASTERLUKE"},
            {"Jamal","GRANDMASTERLUKE"},
            {"GL Palp","SITHPALPATINE"  },
            {"SEEP","SITHPALPATINE"  },
            {"SEE","SITHPALPATINE"  },
            {"Sith Eternal","SITHPALPATINE"  },
            {"Admiral Piett","ADMIRALPIETT" },
            {"Piett","ADMIRALPIETT" }
        };
        public CharacterStrings() { }
    }
}
